apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-apps-raj
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-apps-test
  source:
    path: deploys
    repoURL: 'https://github.com/rajathy/testmeargo.git'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
