apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-apps
spec:
  destination:
    name: docker-desktop
    namespace: argo-apps
  source:
    path: deploys
    repoURL: 'https://github.com/rajathy/testmeargo.git'
    targetRevision: main
  sources: []
  project: default
  Namespace: argo-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
