apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: testargonew
  name: testargonew
  namespace: argonewns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testargo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testargo
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
