apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: argotest
  name: testdeploy1
  namespace: argo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testargo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testargo
    spec:
      containers:
      - image: nginx
        name: nginx-image
        resources: {}
status: {}
