apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: testargo
  name: testargo
  namespace: argons
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testargo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testargo
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
